config/routes.rb
Rails.application.routes.draw do

  root to: "articles#index"
  get '/about', to: 'static_pages#about'
  get '/books', to: 'static_pages#books'
  get '/tools', to: 'static_pages#tools'

  get '/mind', to: 'articles#mind'
  get '/body', to: 'articles#body'
  get '/soul', to: 'articles#soul'
  get '/prosperity', to: 'articles#prosperity'

  resources :author_sessions, only: [:new, :create, :destroy]
  get 'admin', to: 'author_sessions#new'
  get 'logout', to: 'author_sessions#destroy'

  resources :articles, path: :pixels do
    resources :comments
  end
  resources :tags, param: :name
  resources :authors

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include ActionView::Helpers
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  default_scope -> { order(created_at: :desc) }
  validates :title, presence: true
  validates :hover_text, presence: true
  validates :category, presence: true
  validates :body, presence: true
  has_attached_file :image, styles: { medium: "478x478", thumb: "100x100", pixel: "16x16"}
  validates_attachment_content_type :image, :content_type => ['image/jpg', 'image/jpeg', 'image/png']
  before_save :downcase_category

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect{|name| Tag.find_or_create_by(name: name)}
    self.tags = new_or_found_tags
  end

  def downcase_category
    self.category.downcase!
  end

  def increment_view_count
    if self.view_count.nil?
      self.update_attribute('view_count', 1)
    else
      self.update_attribute('view_count', self.view_count += 1)
    end
  end

  def intro
    truncate(strip_tags(RedCloth.new(self.body).to_html), length: 200)
  end

  def previous
    Article.where(['id < ?', id]).first
  end

  def next
    Article.where(['id > ?', id]).last
  end

end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  default_scope -> { order(created_at: :desc) }
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :taggings
    has_many :articles, through: :taggings

    def to_s
      name
    end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  before_filter :require_login, only: [:new, :create, :destroy, :update, :edit]

  def index
    @articles = Article.all
    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
    @article.increment_view_count
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash.notice = "'#{@article.title}' has been created."
      redirect_to article_path(@article)
    else
      flash.now[:notice] = "Unable to create new article."
      render :new
    end
  end

  def destroy
    @article = Article.find(params[:id])
    flash.notice = "'#{@article.title}' has been deleted."
    @article.destroy
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    flash.notice = "'#{@article.title}' has been updated."
    redirect_to article_path(@article)
  end

  def mind
    @articles = Article.where(category: 'mind')
  end

  def body
    @articles = Article.where(category: 'body')
  end

  def soul
    @articles = Article.where(category: 'soul')
  end

  def prosperity
    @articles = Article.where(category: 'prosperity')
  end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')
    else
      flash.now.notice = 'Login failed.'
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(articles_path, notice: 'Logged out')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end

    def zero_authors_or_authenticated
      unless Author.count == 0 || current_user
        redirect_to root_path
        return false
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_login, except: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save
    redirect_to article_path(@comment.article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    flash.notice = "#{@comment.author_name}'s comment has been deleted."
    @comment.destroy
    redirect_to article_path(@article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def books
  end

  def tools
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :require_login, only: [:index, :destroy]

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find_by(name: params[:name])
    @articles = @tag.articles
  end

  def destroy
    @tag = Tag.find(params[:id])
    flash.notice = "'#{@tag.name}' has been deleted."
    @tag.destroy
    redirect_to tags_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def textile(text)
    RedCloth.new(html_escape(text)).to_html
  end

  def intro(text)
    paras = text.split /\n\n/
    textile paras[0]
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def article_params
    params.require(:article).permit(:id, :title, :hover_text, :image, :body, :tag_list, :category)
  end

end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_comment.html.erb
<% @comments = @article.comments.paginate(:page => params[:page], :per_page => 3) %>

<% @comments.each do |comment| %>
  <div>
    <span class="comment-name"><%= comment.author_name %></span>
    <span class="comment-time"> • <%= distance_of_time_in_words(Time.now, comment.created_at) %> ago</span>
    <% if logged_in? %>
      <%= link_to 'delete comment', article_comment_path(@article, comment), method: :delete, data: {confirm: "Are you sure that you want to delete this comment?"} %>
    <% end %>
    <p class="comment"><%= comment.body %></p>
  </div>
<% end %>

<%= will_paginate @comments%>

app/views/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

var disqus_config = function () {
  s.src = '//lifeperpixel.disqus.com/embed.js';
  this.page.url = '<%= article_url(@article) %>';
  this.page.identifier = '<%= @article.id %>';
  this.page.title = '<%= @article.title %>'
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = '//lifeperpixel.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/articles/_form.html.erb
<%= form_for(@article, html: {multipart: true}) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@article.errors.count, "error") %> prohibited this pixel from being saved:</h3>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :hover_text %><br>
    <%= f.text_field :hover_text %>
  </p>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :image, "Attach an Image" %><br>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit "Create Pixel" %>
  </p>
<% end %>

app/views/articles/_listing.html.erb
<div class="listings">
<% @articles.each do |article| %>
  <div class='post' id= <%= "post_#{article.id}" %> title= "<%= article.hover_text %>" >
    <%= image_tag article.image.url(:medium) %>
    <h1><%= link_to article.title, article_path(article), class: 'article_title' %></h1>
    <p>
      <%= article.intro %>
      <em><%= link_to "read more", article_path(article) %></em>
    </p>
  </div><hr>
<% end %>
</div>

app/views/articles/_prevnext.html.erb
  <div class='row prev-next-links'>
    <div class='col-xs-6 col-sm-6 col-md-6'>
      <% if @article.previous %>
        <%= link_to @article.previous do %>
          <p class="prev-next-buttons"><<  Previous</p>
          <%= image_tag @article.previous.image(:thumb) %><br>
          <p class="button-title"><%= @article.previous.title %></p>
        <% end %>
      <% end %>
    </div>
    <div class='col-xs-6 col-sm-6 col-md-6'>
      <div class='pull-right'>
      <% if @article.next %>
        <%= link_to @article.next do %>
          <p class="prev-next-buttons">Up Next  >></p>
          <%= image_tag @article.next.image(:thumb) %>
          <p class="button-title"><%= @article.next.title %></p>
          <% end %>
      <% end %>
      </div>
    </div>
  </div>

app/views/articles/body.html.erb
<% provide(:title, "Body | Life Per Pixel") %>
<%= image_tag('body_header.jpg', class: "header") %><br><br>
<%= render partial: 'listing' %>

app/views/articles/edit.html.erb
<% provide(:title, "Life Per Pixel") %>
<h1>Edit Post</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<%= render partial: 'listing' %>

app/views/articles/mind.html.erb
<% provide(:title, "Mind | Life Per Pixel") %>
<%= image_tag('mind_header.jpg', class: "header") %><br><br>
<%= render partial: 'listing' %>

app/views/articles/new.html.erb
<% provide(:title, "Life Per Pixel") %>
<h1>Create a New Pixel</h1>
<%= render partial: 'form' %>

app/views/articles/prosperity.html.erb
<% provide(:title, "Prosperity | Life Per Pixel") %>
<%= image_tag('prosperity_header.jpg', class: "header") %><br><br>
<%= render partial: 'listing' %>

app/views/articles/show.html.erb
<div id= <%= "post_#{@article.id}" %> title= "<%= @article.hover_text %>" >
  <%= image_tag @article.image.url(:original) %>
  <h1><%= @article.title %></h1>
  <p><%= raw textile @article.body %></p><br>
  <p class="tags">
    Tags
    <% @article.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag.name) %>
    <% end %>
  </p>
</div>
<hr>
<%= render partial: 'prevnext' %>
<br><br>
<div class="comment-section">
  <h2>Let Us Know Your Thoughts!</h2>
  <%= render partial: 'disqus' %>
</div>

<!-- OLD COMMENTS SECTION
<div class="comment-section">
  <h2>Let Us Know Your Thoughts!</h2>
  <h3><%= @article.comments.size %> Comments</h3>
  <hr>

  <div class="comments">
    <%= render partial: 'articles/comment' %><br>
    <%= render partial: 'comments/form' %><br>
  </div>
</div>
-->

  <% if logged_in? %>
    <%= link_to "Edit pixel", edit_article_path(@article) %><br>
    <%= link_to "Delete pixel", article_path(@article), method: :delete, data: {confirm: "Are you sure that you want to delete this post?"} %>
    <br><br>
  <% end %>

app/views/articles/soul.html.erb
<% provide(:title, "Soul | Life Per Pixel") %>
<%= image_tag('soul_header.jpg', class: "header") %><br><br>
<%= render partial: 'listing' %>

app/views/author_sessions/new.html.erb
<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %><br>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %><br>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_for(author) do |f| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h3>Join the discussion</h3>
<%= form_for [ @article, @comment ] do |f| %>
  <p><%= f.text_field :author_name, placeholder: "Enter Name" %></p>
  <p><%= f.text_area :body, placeholder: "Join the discussion...", rows: 5 %></p>
  <p><%= f.submit "Share" %></p>
<% end %>

app/views/layouts/application.html.erb
<% provide(:title, "Life Per Pixel") %>
<!DOCTYPE html>
<html lang='en'>
  <head>

    <!-- Meta Tags & Title -->
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, minimum-scale=1">

    <%= favicon_link_tag 'favicon.ico' %>

    <!-- Stylesheets -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans+Condensed:300">

    <!-- Javascript  -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

    <!-- RSS -->
    <%= auto_discovery_link_tag :rss, articles_url(:format => :rss) %>

  </head>

  <body>

    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
    			<a id="menu-toggle" href="#" class="navbar-toggle">
    				<span class="sr-only">Toggle navigation</span>
    			  <span class="icon-bar"></span>
    			  <span class="icon-bar"></span>
    			  <span class="icon-bar"></span>
    			</a>
          <%= image_tag 'lifelogo_50_gray.png', class: "minilogo" %>
    		</div>
        <div id="sidebar-wrapper" class="navbar navbar-fixed-left sidebar-toggle">
          <br>
          <%= link_to image_tag('lifelogo_125_gray.png', class: "logo"), root_path %>
          <ul class="sidebar-nav">
            <li><%= link_to mind_path do %><div class='mindsq pixel'></div>Mind<% end %></li>
            <li><%= link_to body_path do %><div class='bodybar'></div><div class='bodysq pixel'></div>Body<% end %></li>
            <li><%= link_to soul_path do %><div class='soulbar'></div><div class='soulsq pixel'></div>Soul<% end %></li>
            <li><%= link_to prosperity_path do %><div class='propbar'></div><div class='propsq pixel'></div>Prosperity<% end %></li>
          </ul>
          <div class="grid"></div>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class='row'>

        <div class='col-md-10 content'>
          <p class="flash"><%= flash.notice %></p>
          <%= yield %>
        </div>

        <div class='col-md-2 col-md-offset-10 right-sidebar sticky'>
          <div class="sticky-sidebar">
            <% if logged_in? %>
              Admin mode
              <%= link_to "(logout)", logout_path %><br>
              <%= link_to "Create a New Article", new_article_path, class: 'new_article' %><br>
            <% end %>
            <br>
            <div class='about'>
              <%= link_to image_tag('about_us3.png'), about_path %>
            </div>
            <div class='categories'>
              <h1>Categories</h1>
              <ul>
                <li><%= link_to tag_path('popular') do %><div class='pixel' style='background-color: #2FB8FF;'></div>Popular<% end %></li>
                <li><%= link_to tag_path('relationships') do %><div class='pixel' style='background-color: #FE89F2;'></div>Relationships<% end %></li>
                <li><%= link_to tag_path('happiness') do %><div class='pixel' style='background-color: #16DFCD;'></div>Happiness<% end %></li>
                <li><%= link_to tag_path('spirituality') do %><div class='pixel' style='background-color: #6174EC;'></div>Spirituality<% end %></li>
                <li><%= link_to tag_path('finance') do %><div class='pixel' style='background-color: #FFB66E;'></div>Finance<% end %></li>
                <li><%= link_to tag_path('health') do %><div class='pixel' style='background-color: #91F6FE;'></div>Health<% end %></li>
                <li><%= link_to tag_path('creativity') do %><div class='pixel' style='background-color: #4566BA;'></div>Creativity<% end %></li>
              </ul>
            </div><br>
            <div>
              <%= link_to image_tag('books.jpg'), books_path %>
            </div><br>
            <div>
              <%= link_to image_tag('tools.jpg'), tools_path %>
            </div>
            <div class='email-newsletter'>
              <form class="email-form">
                <input type="text" id="email" name="email" placeholder="Enter Email">
                <button>Sign Up</button>
                <div class="message"></div>
              </form>
            </div>
          </div>
        </div>

      </div>
    </div>

  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About | Life Per Pixel") %>
<%= image_tag('about_header.jpg') %>
<p>Find out more about us...</p>

app/views/static_pages/books.html.erb
<% provide(:title, "Books | Life Per Pixel") %>
<%= image_tag('books_header.jpg') %>
<h3 class='books-subheader'>Top Spiritual Books That Will Change Your View of the World</h3><br>
<div class="books">

  <div class= "row">
    <div class="col-md-5">
      <%= link_to 'http://www.amazon.com/gp/product/1608871576/' do %>
        <div class="book-image"><%= image_tag('journey.jpg') %></div>
        <div class="book-rating"><%= image_tag('99.png') %></div>
      <% end %>
    </div>
    <div class="col-md-7 tool-description">
      <h2><%= link_to 'The Journey Within', 'http://www.amazon.com/gp/product/1608871576/' %></h2>
      <h4>by Radhanath Swami</h4>
      Pellentesque a tincidunt est. Morbi tristique ligula ac suscipit interdum.
      Integer ultricies neque quis ligula efficitur sagittis.
      Aliquam a convallis sem, ac tempor quam.Sed gravida interdum massa,
      sed auctor tellus molestie at. Nunc interdum sapien sit amet dui sodales,
      et interdum urna accumsan.
    </div>
  </div><hr>

  <div class= "row">
    <div class="col-md-5">
      <%= link_to 'http://www.amazon.com/Fervent-Womans-Serious-Specific-Strategic/dp/1433688670' do %>
        <div class="book-image"><%= image_tag('fervent.jpg') %></div>
        <div class="book-rating"><%= image_tag('93.png') %></div>
      <% end %>
    </div>
    <div class="col-md-7 tool-description">
      <h2><%= link_to "Fervent: A Woman's Battle Plan to Serious, Specific and Strategic Prayer", 'http://www.amazon.com/Fervent-Womans-Serious-Specific-Strategic/dp/1433688670' %></h2>
      <h4>by Priscilla Shirer</h4>
      Pellentesque a tincidunt est. Morbi tristique ligula ac suscipit interdum.
      Integer ultricies neque quis ligula efficitur sagittis.
      Aliquam a convallis sem, ac tempor quam.Sed gravida interdum massa,
      sed auctor tellus molestie at. Nunc interdum sapien sit amet dui sodales,
      et interdum urna accumsan.
    </div>
  </div><hr>

  <div class= "row">
    <div class="col-md-5">
      <%= link_to 'http://www.amazon.com/No-Greater-Love-Mother-Teresa/dp/1577312015/' do %>
        <div class="book-image"><%= image_tag('nogreaterlove.jpg') %></div>
        <div class="book-rating"><%= image_tag('90.png') %></div>
      <% end %>
    </div>
    <div class="col-md-7 tool-description">
      <h2><%= link_to 'No Greater Love', 'http://www.amazon.com/No-Greater-Love-Mother-Teresa/dp/1577312015/' %></h2>
      <h4>by Mother Teresa</h4>
      Pellentesque a tincidunt est. Morbi tristique ligula ac suscipit interdum.
      Integer ultricies neque quis ligula efficitur sagittis.
      Aliquam a convallis sem, ac tempor quam.Sed gravida interdum massa,
      sed auctor tellus molestie at. Nunc interdum sapien sit amet dui sodales,
      et interdum urna accumsan.
    </div>
  </div><hr>

  <div class= "row">
    <div class="col-md-5 books">
      <%= link_to 'http://www.amazon.com/gp/product/1590309634/' do %>
        <div class="book-image"><%= image_tag('livingbeautifully.jpg') %></div>
        <div class="book-rating"><%= image_tag('88.png') %></div>
      <% end %>
    </div>
    <div class="col-md-7 tool-description">
      <h2><%= link_to 'Living Beautifully: with Uncertainty and Change', 'http://www.amazon.com/gp/product/1590309634/' %></h2>
      <h4>by Pema Chödrön</h4>
      Pellentesque a tincidunt est. Morbi tristique ligula ac suscipit interdum.
      Integer ultricies neque quis ligula efficitur sagittis.
      Aliquam a convallis sem, ac tempor quam.Sed gravida interdum massa,
      sed auctor tellus molestie at. Nunc interdum sapien sit amet dui sodales,
      et interdum urna accumsan.
    </div>
  </div><hr>

  <div class= "row">
    <div class="col-md-5">
      <%= link_to 'http://www.amazon.com/Autobiography-Yogi-P-Yogananda/dp/8120725247' do %>
        <div class="book-image"><%= image_tag('yogi.jpg') %></div>
        <div class="book-rating"><%= image_tag('85.png') %></div>
      <% end %>
    </div>
    <div class="col-md-7 tool-description">
      <h2><%= link_to 'Autobiography of a Yogi', 'http://www.amazon.com/Autobiography-Yogi-P-Yogananda/dp/8120725247' %></h2>
      <h4>by Paramahansa Yogananda</h4>
      Pellentesque a tincidunt est. Morbi tristique ligula ac suscipit interdum.
      Integer ultricies neque quis ligula efficitur sagittis.
      Aliquam a convallis sem, ac tempor quam.Sed gravida interdum massa,
      sed auctor tellus molestie at. Nunc interdum sapien sit amet dui sodales,
      et interdum urna accumsan.
    </div>
  </div><hr>

</div>

app/views/tags/index.html.erb
<h1>All Tags</h1>
<ul>
  <% @tags.each do |tag| %>
    <li>
      <%= tag.name %>
      <%= link_to 'delete', tag_path(tag), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<% provide(:title, "#{@tag.name.capitalize} | Life Per Pixel") %>
<h1><%= @tag.name.upcase %></h1>

<%= render partial: 'articles/listing' %>